### ISSUE TITLE
Serialization of Instant seems to throw exceptions when when @JsonFormat is used

### ISSUE THREAD

**Issue by knes1** [FasterXML/jackson-datatype-jsr310#69]
Here's the test case that results with exception:

```
public class TestSerialization {

	public static class InstantTest {

		@JsonFormat(shape = JsonFormat.Shape.STRING, pattern="yyyy-MM-dd'T'HH:mm:ss.SSSXXX", timezone = "UTC")
		private Instant instant;

		public Instant getInstant() {
			return instant;
		}

		public void setInstant(Instant instant) {
			this.instant = instant;
		}
	}

	@Test
	public void testSerialization() throws JsonProcessingException {
		ObjectMapper om = new ObjectMapper();
		om.registerModule(new JavaTimeModule());

		InstantTest i = new InstantTest();
		i.setInstant(Instant.now());

		om.writeValueAsString(i);
	}
}
```

The version I used is 2.6.5. I looks like the serializer is initialized with formatter that has no time zone set (e.g. it does not pick up time zone from @JsonFormat's timezone field). This causes exception when trying to format the Instant.

```
com.fasterxml.jackson.databind.JsonMappingException: Unsupported field: YearOfEra (through reference chain: InstantTest["instant"])

	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:199)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:683)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3559)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2927)
	at TestSerialization.testSerialization(TestSerialization.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
Caused by: java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: YearOfEra
	at java.time.Instant.getLong(Instant.java:603)
	at java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:298)
	at java.time.format.DateTimeFormatterBuilder$NumberPrinterParser.format(DateTimeFormatterBuilder.java:2543)
	at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2182)
	at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1744)
	at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1718)
	at com.fasterxml.jackson.datatype.jsr310.ser.InstantSerializerBase.serialize(InstantSerializerBase.java:93)
	at com.fasterxml.jackson.datatype.jsr310.ser.InstantSerializerBase.serialize(InstantSerializerBase.java:39)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:693)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:675)
	... 26 more
```

**Comment by knes1** [comment]
Just noticed this comment in TestInstantSerialization test:
```
/* 22-Jun-2015, tatu: I'll be damned if I understand why pattern does not
 *    work here... but it doesn't. Someone with better date-fu has to come
 *    and fix this; until then I will only verify that we can force textual
 *    representation here
 */
```
Let me provide the required date-fu :) The issue is that in order to format an Instant, which is bascially a timestamp, the formatter needs to be initialized with time zone, otherwise it will not know how to calculate correct values for time fields (e.g. hours). Formatter defined in JSR310FormattedSerializerBase.createContextual(...) is not initialized with time zone. It should pick it up from JsonFormat annotaion and then call something along the lines of:
`
dtf = dtf.withZone(format.getTimeZone().toZoneId());`

**Comment by Drizzt321** [comment]
This is exactly what I just came to create an issue for, glad it's fixed :)  Unfortunately it's not in 2.7.3, anyone know when the next version will released onto Maven Central?

**Comment by cowtowncoder** [comment]
@Drizzt321 Would be in 2.7.4, not yet sure when that will be released:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.7.4

possibly within next couple of weeks.

**Comment by Drizzt321** [comment]
Thanks, I'll keep an eye out.
