### ISSUE TITLE
Unable to load the class

### ISSUE THREAD

**Issue by pradhakrishnan** [FasterXML/jackson-datatype-jsr310#94]
I have an issue with jsr310 library in tomcat. my jdk is not able to load the class

```

15:41:27,752 ERROR[org.springframework.web.context.ContextLoader] (localhost-startStop-1) Context initialization failed
java.lang.UnsupportedClassVersionError: com/fasterxml/jackson/datatype/jsr310/JavaTimeModule : Unsupported major.minor version 52.0 (unable to load class com.fasterxml.jackson.datatype.jsr310.JavaTimeModule)
	at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2961)
	at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1210)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1690)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
	at java.lang.Class.getDeclaredMethods(Class.java:1860)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:571)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:490)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:474)

```

Any idea?

**Comment by cowtowncoder** [comment]
Sounds like you are running on old JVM, Java 7 or so. This module requires Java 8 and bytecode is compiled on that as well.

**Comment by pradhakrishnan** [comment]
Yes my application is running in 1.7 and we need to deserialize offset time (java 8) in our application. so i have used this library.

**Comment by cowtowncoder** [comment]
@pradhakrishnan I don't think you understand: those classes are only included in JDK 8. It would not work on JDK 1.7. At all. So you do not use this module since it can never work on pre-Java-8 platform.

There is a Java 7 backport of some kind (http://www.threeten.org/threetenbp/) available, and someone may have created alternate version of this module to support. Perhaps you were thinking of that.
